version: '3.9'

services:
    metastore-pg:
        image: postgres:16.2-alpine
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        healthcheck:
            test: ['CMD', 'psql', '-U', '${POSTGRES_USER}', '${POSTGRES_DB}']
        ports:
            - '5432:5432'
        volumes:
            - metastore-pg:/var/lib/postgresql/data/

    metastore:
        build:
            context: .
            dockerfile: docker/Dockerfile
        depends_on:
            metastore-pg:
                condition: service_healthy
        environment:
            - DATABASE_HOST=metastore-pg
            - DATABASE_DB=${POSTGRES_DB}
            - DATABASE_USER=${POSTGRES_USER}
            - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - S3_ENDPOINT_URL=http://minio:9000
            - S3_BUCKET
            - S3_PREFIX
        ports:
            - '9083:9083'

    minio:
        image: minio/minio
        container_name: minio
        environment:
            - MINIO_ROOT_USER=test
            - MINIO_ROOT_PASSWORD=testSecret
            - MINIO_DOMAIN=minio
        ports:
            - 9001:9001
            - 9000:9000
        command: ['server', '/data', '--console-address', ':9001']
        networks:
            default:
                aliases:
                    - warehouse.minio # must be name of iceberg warehouse bucket on minio, otherwise host is not found



volumes:
    metastore-pg:
        name: 'metastore-pg'